### PR TITLE
Add sortBy option for a column

### PR DESCRIPTION
**Pull request by marti4ka**
Hi @amcdnl,

the background for #222 is that we have custom columns with links and icons with tooltips. The sorting wasn't working properly as we don't pass a string, but an object. I added the sortBy property, so that we can sort the given column by a special property (the text of the link or the tooltip). I changed the `sort.html` example and you can see what I mean.

I don't know if many people will use this and if it is a nice solution, but these changes work for our project and are backwards-compatible. What is your opinion? Do you think there is a better way to do this?

Thanks in advance!

### CODE REVIEW

**Comment by amcdnl** [comment]
@marti4ka looks good, thanks for your contribution!

Side note: I see u work at SAP SE, you guys use this project?

**Comment by marti4ka** [comment]
Yup, we build a small tool for internal usage and at first we only wanted to resize the columns of a table. Then it escalated :D and we needed a tree, icons, sorting...

**Comment by amcdnl** [comment]
Isn't that always the case? haha!

Have you checked out the our angular2 version of this?

**Comment by marti4ka** [comment]
Yes, I saw it 👍 However, our project was already using angular1, so this version of the angular-data-table suits perfectly :blush:

**Pull request merged**
