### PR TITLE
Scope is not destroyed when the row is rerendered #218

### PR DESCRIPTION
**Pull request by Charles-BARDIN**
When 'cell.row' is modified, the old scope of the cell is destroyed, and a new one is created.

### CODE REVIEW

**Comment by amcdnl** [comment]
Woah! Awesome! Thanks for your contribution!

**Comment by ghost** [comment]
Thanks for merging.
Can you publish a new version on bower and other package managers, please?

**Comment by amcdnl** [comment]
Yup, in progress.

**Comment by ghost** [comment]
Thank you ;)

**Comment by amcdnl** [comment]
done.

**Pull request merged**
