### PR TITLE
(fix): fixing BodyController isSelected method for multiselect.

### PR DESCRIPTION
**Pull request by ngodfraind**
It's me... again.

I ran into some problems with the multiselect when I was changing pages for some reason.
The this.select.indexOf(xxx) never found any object (and they were existing) so my checkboxes were unchecked. I don't know what goes wrong.

http://stackoverflow.com/questions/12604062/javascript-array-indexof-doesnt-search-objects

This is not a pretty fix but it worked well. It also somehow fixed the bug I had with the header select.
I assume I'd have the same problem with the simple select but I didn't change the else bracket.

edit: meh, I can't uncheck rows properly anymore with this. I'll looks at it.

### CODE REVIEW

**Comment by amcdnl** [comment]
Can you make a demo of this happening? 

That fix has some other unintended consequences and performance issues too so we will need to come up with something else.

**Comment by ngodfraind** [comment]
http://jsfiddle.net/ngodfraind/cxcbaf8f/

On this one, the selection will disappear once you change pages (check some rows, go to page 2, go back to page 1). The behaviour changes again if I populate the 'selected' array myself (I'll make a jsfiddle too if you want).

edit: nevermind. I remember why it failed when I populated the array myself. It was because I don't understand angular yet and did silly things.

**Comment by ngodfraind** [comment]
Any news ?

**Comment by amcdnl** [comment]
did you merge another feature into this PR? Is your issue still relevant?

**Comment by ngodfraind** [comment]
The issue is still relevant, but that PR doesn't fix all the problem. Checking rows becomes ok, but you can't uncheck them properly anymore.

I didn't look for a fix since I made the PR so I have no idea why it behave like this.

**Comment by ngodfraind** [comment]
I'm closing it because I have the on header checbox change in that one.
Also there are other pr/issue for this problem.

**Pull request closed without merging**
