### PR TITLE
Display data changes in UI

### PR DESCRIPTION
**Pull request by BenBrostoff**
This changeset allows rows to briefly change row color based on data changing. This solution is what I'm thinking of <a href="https://github.com/Swimlane/angular-data-table/issues/125"> based on this feature request I had here </a>, but please let me know what solution makes the most sense. I updated the <code>updating</code> example with the changes.

As an aside, I believe this feature would get broadly used as I'd think there a number of applications that use angular-data-table and are consistently polling for updated numbers (it's at least true for my use case).

### CODE REVIEW

**Comment by amcdnl** [comment]
Thanks for the PR!  Although, I'm curious why you wouldn't just use a custom cell template and bind a css class to that property?

**Comment by BenBrostoff** [comment]
I did consider that, but it seems like if you're inside a cell you need to access the parent with <code> .dt-row </code> assuming you want to alter the entire row's styling (in which case you'd need something like jQuery's <code>closest </code>)? Also, it might be nice to have the ability do assign css classes to entire rows without having to go through cells for ease of use. 

Apologies if I'm overthinking this and using a cell template is the way to go here.

**Comment by amcdnl** [comment]
@BenBrostoff no not at all. so your wanting to do it at the row level? I'd probably use a class for each cell and then just apply it like that. Would that suit your needs?

I hesitate to add this code since its just a specific use case. I think a generic row class would be a better solution if my suggestion doesn't work.

**Comment by BenBrostoff** [comment]
Ah, that makes sense; appreciate the feedback here. I'll close this PR and take your advice, thanks again!

**Pull request closed without merging**
