### PR TITLE
Event trigger

### PR DESCRIPTION
**Pull request by ngodfraind**
This PR allows to register a callback on 2 events.
- changes on the header checkbox (on-header-checkbox-changed)
- uncheck a row (on-uncheck)

I'm not sure what's the proper way to do it (and what would be the correct names to use), but it's usefull if you want to do ajax calls when you click on somewhere.

### CODE REVIEW

**Comment by amcdnl** [comment]
Thanks for the PR!

A uncheck event is a tad odd, what are you trying to accomplish maybe there is a different way?

**Comment by ngodfraind** [comment]
I'm doing ajax calls on checkboxes changes (because the pager doesn't work well yet with the multiselect).

**Comment by amcdnl** [comment]
I believe the checkbox event fires on any change, why not just use that?

**Comment by ngodfraind** [comment]
The "on-select" event only fires on select. I couldn't find an "on-change" event or something like that. But maybe I didn't understand what was going on.

I couldn't find an event for the header checkbox either.

**Comment by amcdnl** [comment]
Sorry, been busy on other projects. I'll look into this in the next week.

**Comment by ngodfraind** [comment]
I'll do something cleaner.

**Pull request closed without merging**
