### PR TITLE
Fixed bug for reordering tables

### PR DESCRIPTION
**Pull request by frontich**
howdy...
i am new to git ... so i dont know the manners of good behaviour :) .... still learning... if you want you can merge with my code .. i have added an e2e protractor dependency and fixed bug from the title...let me know your decision...

### CODE REVIEW

**Comment by amcdnl** [comment]
@Fr0ntich Welcome and thanks for the commit!  Curious: why did you add e2e w/o any tests?

Side note: the files in the dist folder are automatically generated from those in the src file, no need to edit those ;)

**Comment by frontich** [comment]
@amcdnl t i thought maybe e2e tests could be implemented for the demo page, because demo site has some issues... You need to tell me if you see this as candidate for e2e tests.  

about  side note :+1:

**Comment by amcdnl** [comment]
Absolutely but lets not add it until we have some actual tests for it.  Can u remove from this PR as it is not related ot this fix.

**Comment by frontich** [comment]
i removed protractor dependency untill i have some actual tests for demo page

**Comment by marjan-georgiev** [comment]
Looks good, thanks!

**Comment by frontich** [comment]
You're welcome :)

**Pull request merged**
