### PR TITLE
Adding an on-deselect event callback

### LINKED ISSUE #185: Suggestion: Callback when unselecting a row.
There is a callback when a row gets selected, on-select, but when using multiselect, a similar callback indicating what row was just unselected would be quite useful.

### PR DESCRIPTION
**Pull request by dlarsson**
Fixes #185 . Get a callback when deselecting a row in the table.

My editor seems to have removed trailing spaces, so the diff is a bit bigger than it needs to be, sorry about that.

### CODE REVIEW

**Comment by amcdnl** [comment]
Why not just look for select events and diff?

**Comment by dlarsson** [comment]
The select event only fires when a row is selected, so if I want to perform some action at deselection, I don't see how I could do that? Or did I miss something?

**Comment by amcdnl** [comment]
oh I see, nm forgot about checkboxes. maybe a change event would be better for this?

**Comment by amcdnl** [comment]
didn't mean to close

**Comment by dlarsson** [comment]
A change event would work as well, yes =)

**Comment by amcdnl** [comment]
will u update to that please?

**Comment by dlarsson** [comment]
Yes, I'll fix. Just a bit crazy work wise at the moment, but I'll try spend
some time next week.

2016-05-27 0:51 GMT+02:00 Austin notifications@github.com:

**Comment by amcdnl** [comment]
Closing due to in-activity

**Pull request closed without merging**
