### PR TITLE
Bower package registered and bower file added.

### PR DESCRIPTION
**Pull request by vishwajeetv**

### CODE REVIEW

**Comment by vishwajeetv** [comment]
The package can be installed using `bower install angular-data-table`

**Comment by marjan-georgiev** [comment]
The bower package points to your fork. Please update.

**Comment by awartoft** [comment]
Hmm, i could use this as well, please update

**Comment by amcdnl** [comment]
still points to your fork

**Comment by awartoft** [comment]
And the author is wrong >_<

**Comment by vishwajeetv** [comment]
Bower package is now pointing to this repository.
`bower install angular-data-table` would install this package.
Ah, needed to unregister and register again!! :smile:

**Comment by amcdnl** [comment]
author is wrong still ;)

**Comment by vishwajeetv** [comment]
I was confused about it, whether I should add @swimlane or @amcdnl

**Comment by vishwajeetv** [comment]
Sorry for the inconvenience caused by this, I could have been more careful while creating the PR.

**Comment by vishwajeetv** [comment]
Besides, I was confused, I thought a repo without having bower.json can not get registered ( I was wrong about it ), I wanted to use this in my project, and wanted something quick - up & running ( I am using Yeoman's workflow ) so I thought rather than waiting for PR to get accepted, I can just get along with pointing it to my repo.

Anyway..

**Comment by amcdnl** [comment]
done

**Pull request closed without merging**
